version: '3'
services:


  rest-service-dashboard:
    build: dashboard_x
    # image: my-service-cluster/rest-service-dashboard
    image: 10.100.1.38:5000/my-rest-service-dashboard
    restart: always
    ports:
      - 16600:16600
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure
    networks:
      - my-network


  # kafka:
  #   container_name: kafka
  #   image: spotify/kafka:latest
  #   ports:
  #    - 2181:2181
  #    - 9092:9092
  #   networks:
  #     - my-network

  # redis:
  #   image: redis
  #   ports:
  #     - 6379:6379
  #   deploy:
  #     replicas: 1
  #     restart_policy:
  #       condition: on-failure
  #   networks:
  #     - my-network
    

  rest-service-sync:
    build: rest-service-sync
    # image: my-service-cluster/rest-service-sync
    image: 10.100.1.38:5000/my-rest-service-sync
    restart: always
    ports:
      - 16601:16601
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure
    networks:
      - my-network

  rest-service-analysis:
    build: rest-service-analysis
    # image: my-service-cluster/rest-service-analysis
    image: 10.100.1.38:5000/my-rest-service-analysis
    restart: always
    ports:
      - 16602:16602
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure
    networks:
      - my-network



networks:
  my-network:
    driver: overlay
    # driver: bridge





  
