version: '3'
services:


  rest-service-dashboard:
    build: dashboard_x
    image: my-service-cluster/rest-service-dashboard
    # image: 10.141.212.25:5555/my-rest-service-dashboard
    restart: always
    ports:
      - 16600:16600
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure
    networks:
      - my-network

  # kafka:
  #   container_name: kafka
  #   image: spotify/kafka:latest
  #   ports:
  #    - 2181:2181
  #    - 9092:9092
  #   networks:
  #     - my-network

  # redis:
  #   image: redis
  #   ports:
  #     - 6379:6379
  #   deploy:
  #     replicas: 1
  #     restart_policy:
  #       condition: on-failure
  #   networks:
  #     - my-network

  rest-service-1:
    build: rest-service-1
    image: my-service-cluster/rest-service-1
    # image: 10.141.212.25:5555/my-rest-service-1
    restart: always
    ports:
      - 16601:16601
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure
    networks:
      - my-network

  rest-service-end:
    build: rest-service-end
    image: my-service-cluster/rest-service-end
    # image: 10.141.212.25:5555/my-rest-service-end
    restart: always
    ports:
      - 16602:16602
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure
    networks:
      - my-network



networks:
  my-network:
    # driver: overlay
    driver: bridge





  
